spring:
  datasource:
    url: jdbc:mysql://localhost:3306/guesstest?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
  jpa:
    hibernate:
      ddl-auto: create

server:
  port: 18080

cucumber:
  port: 18080
  context-path:
