spring:
    datasource:
        url: jdbc:mysql://localhost:3306/bbuddydev?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
        password: dbs3cr3t
        testWhileIdle: true
        username: nerd
        validationQuery: SELECT 1
    jpa:
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate:
                default_schema: bbuddydev
                dialect: org.hibernate.dialect.MySQL5Dialect
        show-sql: true

application:
    perPageLimit: 10

server:
  port: 8090
